### ISSUE TITLE
The Ratings of Hotels 

### ISSUE THREAD

**Issue by Vijaykv5** [yelendisuresh/Namaste-React#1]
![Capture](https://user-images.githubusercontent.com/94985341/220334644-7547f3ac-2f3c-444b-b5c3-cdbb735db6d3.PNG)

The Card is Fully Crowded with all the details, May be a space can be provided and the Rating Doesn't Fits for the card , Please change that .
Thanks 
Vijay

**Comment by yelendisuresh** [comment]
First thanks for raising issue , fixed now 
![image](https://user-images.githubusercontent.com/19219572/220639173-ccaad3a2-29c4-4ed8-87e5-ace7af82dc6d.png)

**Comment by yelendisuresh** [comment]
fixed

**Comment by Vijaykv5** [comment]
Great :)
